package vaccine.registration.system;

import java.awt.*;
import javax.swing.*;

public class PeopleRegisterAccount extends javax.swing.JFrame {

    /**
     * Creates new form People_RegisterAccount
     */
    public PeopleRegisterAccount() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_register_account = new javax.swing.JPanel();
        lbl_logo = new javax.swing.JLabel();
        lbl_register_a_new_account = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        lbl_phone_number = new javax.swing.JLabel();
        txt_phone_number = new javax.swing.JTextField();
        lbl_nationality = new javax.swing.JLabel();
        txt_nationality = new javax.swing.JTextField();
        lbl_ic_passport_number = new javax.swing.JLabel();
        txt_ic_passport_number = new javax.swing.JPasswordField();
        lbl_address = new javax.swing.JLabel();
        txt_address = new javax.swing.JTextField();
        lbl_password = new javax.swing.JLabel();
        txt_password = new javax.swing.JTextField();
        btn_register = new javax.swing.JButton();
        btn_back_to_login = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("People Register Account");
        setResizable(false);

        pnl_register_account.setBackground(new java.awt.Color(255, 255, 255));

        lbl_logo.setBackground(java.awt.Color.white);
        lbl_logo.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lbl_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vaccine/registration/system/images/MyVaccine Logo - Blue.png"))); // NOI18N

        lbl_register_a_new_account.setBackground(java.awt.Color.white);
        lbl_register_a_new_account.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lbl_register_a_new_account.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_register_a_new_account.setText("Register A New Account");

        lbl_name.setBackground(java.awt.Color.white);
        lbl_name.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lbl_name.setText("Name");

        txt_name.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(219, 219, 219)));

        lbl_phone_number.setBackground(java.awt.Color.white);
        lbl_phone_number.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lbl_phone_number.setText("Phone Number");

        txt_phone_number.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_phone_number.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(219, 219, 219)));

        lbl_nationality.setBackground(java.awt.Color.white);
        lbl_nationality.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lbl_nationality.setText("Nationality");

        txt_nationality.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_nationality.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(219, 219, 219)));

        lbl_ic_passport_number.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lbl_ic_passport_number.setText("IC / Passport Number");

        txt_ic_passport_number.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_ic_passport_number.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(219, 219, 219)));

        lbl_address.setBackground(java.awt.Color.white);
        lbl_address.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lbl_address.setText("Address");

        txt_address.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_address.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(219, 219, 219)));

        lbl_password.setBackground(java.awt.Color.white);
        lbl_password.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lbl_password.setText("Password");

        txt_password.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txt_password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(219, 219, 219)));

        btn_register.setBackground(new java.awt.Color(73, 161, 236));
        btn_register.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btn_register.setForeground(new java.awt.Color(255, 255, 255));
        btn_register.setText("Register");
        btn_register.setBorder(null);

        btn_back_to_login.setBackground(new java.awt.Color(255, 255, 255));
        btn_back_to_login.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btn_back_to_login.setText("Back to Log In");
        btn_back_to_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_back_to_loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_register_accountLayout = new javax.swing.GroupLayout(pnl_register_account);
        pnl_register_account.setLayout(pnl_register_accountLayout);
        pnl_register_accountLayout.setHorizontalGroup(
            pnl_register_accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_register_accountLayout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(btn_back_to_login, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145)
                .addGroup(pnl_register_accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_address, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nationality, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nationality)
                    .addComponent(txt_phone_number, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_register_accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbl_ic_passport_number)
                        .addComponent(lbl_logo, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                        .addComponent(lbl_register_a_new_account, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_name)
                        .addComponent(txt_name)
                        .addComponent(lbl_phone_number)
                        .addComponent(lbl_address)
                        .addComponent(lbl_password)
                        .addComponent(btn_register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_password)
                        .addComponent(txt_ic_passport_number)))
                .addContainerGap(440, Short.MAX_VALUE))
        );
        pnl_register_accountLayout.setVerticalGroup(
            pnl_register_accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_register_accountLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnl_register_accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_back_to_login, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(lbl_register_a_new_account)
                .addGap(25, 25, 25)
                .addComponent(lbl_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_phone_number)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_phone_number, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_nationality)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_nationality, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_ic_passport_number)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_ic_passport_number, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_address)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_address, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btn_register, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_register_account, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_register_account, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_back_to_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_back_to_loginActionPerformed
        Login backToLogin = new Login();
        backToLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_back_to_loginActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PeopleRegisterAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PeopleRegisterAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PeopleRegisterAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PeopleRegisterAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PeopleRegisterAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back_to_login;
    private javax.swing.JButton btn_register;
    private javax.swing.JLabel lbl_address;
    private javax.swing.JLabel lbl_ic_passport_number;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_nationality;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_phone_number;
    private javax.swing.JLabel lbl_register_a_new_account;
    private javax.swing.JPanel pnl_register_account;
    private javax.swing.JTextField txt_address;
    private javax.swing.JPasswordField txt_ic_passport_number;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_nationality;
    private javax.swing.JTextField txt_password;
    private javax.swing.JTextField txt_phone_number;
    // End of variables declaration//GEN-END:variables
}
